---
- name: Install virtualenv
  pip: name=virtualenv

- name: Install compiled Python packages in virtualenv
  pip:
    requirements: "/home/vagrant/src/requirements/compiled.txt"
    virtualenv: "/home/vagrant/env"
    virtualenv_site_packages: yes

- name: Install docs Python packages in virtualenv
  pip:
    requirements: "/home/vagrant/src/requirements/docs.txt"
    virtualenv: "/home/vagrant/env"
    virtualenv_site_packages: yes

- name: Install performance Python packages in virtualenv
  pip:
    requirements: "/home/vagrant/src/requirements/performance.txt"
    virtualenv: "/home/vagrant/env"
    virtualenv_site_packages: yes

- name: Install some more deps in the virtualenv
  pip:
    virtualenv: "/home/vagrant/env"
    virtualenv_site_packages: yes
    name: "{{ item }}"
  with_items:
    - gunicorn

- name: Update ownership of virtualenv to vagrant
  file:
    owner: vagrant
    group: vagrant
    recurse: yes
    state: directory
    path: "/home/vagrant/env"
