---
- name: Install virtualenv
  pip: name=virtualenv

- name: Make sure global Python packages aren't used in the virtualenv
  file:
    path: /home/vagrant/env/lib/python2.7/no-global-site-packages.txt
    owner: vagrant
    group: vagrant
    mode: 0644
    state: touch

- name: Install pip
  pip:
    name: pip
    version: 8.0.1
    virtualenv: /home/vagrant/env

- name: Install local dependencies in virtualenv
  pip:
    requirements: "{{ item }}"
    virtualenv: /home/vagrant/env
  with_items:
  - /home/vagrant/src/requirements/compiled.txt
  - /home/vagrant/src/requirements/local.txt

- name: Install documentation dependencies in virtualenv
  pip:
    requirements: /home/vagrant/src/requirements/docs.txt
    virtualenv: /home/vagrant/env

- name: Update ownership of virtualenv to vagrant
  file:
    owner: vagrant
    group: vagrant
    recurse: yes
    state: directory
    path: /home/vagrant/env
